### ISSUE TITLE
MySQLdb 没有python3 版本

### ISSUE THREAD

**Issue by ZZinKin** [mtianyan/ArticleSpider#1]
能不能用别的数据库方案

**Comment by mtianyan** [comment]
@ZZinKin 可以，使用mysqlclient。pip安装如果失败推荐前往https://www.lfd.uci.edu/~gohlke/pythonlibs/进行下载，本地安装。

**Comment by wzyonggege** [comment]
pymysql

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
