### ISSUE TITLE
elasticsearch_dsl.exceptions.IllegalOperation

### ISSUE THREAD

**Issue by saler-1** [mtianyan/ArticleSpider#10]
运行model中的文件时，会报错：elasticsearch_dsl.exceptions.IllegalOperation: Index object cannot have multiple types, doc already set, trying to assign article.

**Comment by mtianyan** [comment]
@saler-1  请确认你下载的是elasticsearch-rtf以及安装的elasticsearch dsl 版本:

elasticsearch==5.5.2
elasticsearch-dsl==5.3.0
