### ISSUE TITLE
missing argument grant type

### ISSUE THREAD

**Issue by DrPride** [mtianyan/ArticleSpider#11]
登录知乎时输入密码后出现如题错误，应该是OAuth2机制。

**Comment by mtianyan** [comment]
换chrome浏览器为旧版本60及对应chromedriver驱动，或者改为使用phantomjs都可以解决

**Comment by DrPride** [comment]
我看到消息称selenium不再支持PhantomJS的样子，现在还可以使用吗？
然后我试用了Chrome（63）和Firefox的无头版本，还是显示类似问题。

**Comment by mtianyan** [comment]
@DrPride  我亲测过的，PhantomJS虽然有警告但是依然可以直接用，新版本的chrome不知为何出现这个问题，我换成60成功了，但是毕竟主力浏览器旧版本还得禁止自动更新不顺手，最后屈从于会Warning的PhantomJS，代码里就改一行，把chrome改为PhantomJS
