### ISSUE TITLE
mysql 数据库初始化文件在哪呢

### ISSUE THREAD

**Issue by jackiilong** [mtianyan/ArticleSpider#2]

**Comment by mtianyan** [comment]
如果着急的话，你可以通过item中写定的字段先自行创建数据库表。大概两天后我回家了才可以将sql补上来。

**Comment by jackiilong** [comment]
ok.
还有一个问题，spider抓取到了内容，elasticsearch里面的index数量是0,这会是什么原因呢？

**Comment by mtianyan** [comment]
es的index需要自己手动右键Run es_zhihu系列文件映射成需要的index。

**Comment by jackiilong** [comment]
从哪里右键Run as ?  是哪个页面吗？

**Comment by mtianyan** [comment]
@jackiilong 已经附上了mysql文件。es存入的版本在es分支。然后初始化es索引是执行ArticleSpider/ArticleSpider/models/目录下的三个文件: es_jobbole.py es_lagou.py es_zhihu.py

**Comment by jackiilong** [comment]
ok.
这2个分支有什么区别呢？

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
