### ISSUE TITLE
__init__() got an unexpected keyword argument '_job' 

### ISSUE THREAD

**Issue by Jiahe-J** [mtianyan/ArticleSpider#5]
__init__() got an unexpected keyword argument '_job' 
最新master分支下的 ArticleSpider/spiders/jobbole.py 需更为改 def __init__(self, **kwargs)

**Comment by mtianyan** [comment]
这个问题在scrapyd部署的时候会遇到，确实是一个忘记改掉的bug。谢谢提醒。 @Jiahe-J
