### ISSUE TITLE
这个还是旧版的登陆，新版的已经不适xsrf验证了，变得非常复杂了

### ISSUE THREAD

**Issue by JNULYD** [mtianyan/ArticleSpider#6]
这个还是旧版的登陆，新版的已经不适xsrf验证了，变得非常复杂了

**Comment by mtianyan** [comment]
@JNULYD 已经更新了，经过测试，知乎登录爬取字段可用。

**Comment by rockyfire** [comment]
@mtianyan 新版的那个接口是那里找到的？

**Comment by loadingzxy** [comment]
知乎新版的爬取仍然不可用啊

**Comment by mtianyan** [comment]
当时五月十号我是测试运行好了之后更新上来的，后面知乎应该是又发生了变化。等待我有时间更新一下。

**Comment by mtianyan** [comment]
@loadingzxy  @rockyfire  @JNULYD  已经采用了更通用，简单，变动更小的selenium方式。
